### ISSUE TITLE
Update for Version 2.2, 2.3

### ISSUE THREAD

**Issue by msslava** [MediaSiloNL/CasparCG-PHP-Timecode-Display#1]
Hi, Thanks for share!

I am doing a project on php and your project helped me a lot. But there are a few problems.
I can not get the timecode in server versions 2.2 and 2.3. Could you help with this?
And also: if during the playback of a clip, press the stop, then the time does not stop. It can be fixed?
Thanks!

**Comment by MediaSiloNL** [comment]
Oe... It has been a while since I touched this project to be honest... Nowadays I control everything via NodeJS Apps. I'll try and free up some time to update the code with the bugfixes and add some extra stuff

**Comment by msslava** [comment]
Thank! It would be cool!

**Comment by MediaSiloNL** [comment]
@msslava I've updated all the code to work with current server versions.
I also reworked the whole NodeJS Server file to be more clear.
I recommend you use the new version as this one has some extra issue fixing and better online timing features. If you need anything, just let me know.

**Comment by msslava** [comment]
Really cool! Thank!
Maybe you have the same solution on php for casparcg video previews? 
Now I use https://github.com/kmoskwiak/node-tcp-streaming-server, but it is unstable ...

**Comment by MediaSiloNL** [comment]
@msslava What kind of previews do you need? The livefeed coming from the CasparCG output (That's possible with a FFMpeg Multicast straight from CasparCG; like they do in the client) or web-based previews of content that's currently in the media folder from CCG? (For the last one I use a custom MAM that copies the content to CCG and makes a LowRess for online)

**Comment by msslava** [comment]
I mean the livefeed coming from the CasparCG output (like in client). I want insert it into a web page with minimal delay. All methods known to me have a big delay. In the official client, everything works without delay.

**Comment by MediaSiloNL** [comment]
I've tried to come up with decent alternatives for your problem, but the only thing I can come up with is to start a FFMpeg output on the channel and embed this in the webpage... Just as the client does. The big downside is that it will have a heavy load on the CPU/GPU as it has to transcode it live.
I've also experienced some heavy artifacting in that stream. You could offload it to a different server with a cheap BM card and OBS to generate a post-CasparCG UDP stream. If it doesn't need to be frame-acurate this is a simple alternative. Or you could look into NDI... hhttps://www.newtek.com/ndi/tools/ As CCG supports output to the NDI
